package lexer;
 
/**
 *  This file is automatically generated<br>
 *  - it contains the enumeration of all of the tokens
*/
public enum Tokens {
  BogusToken,Program,Int,BOOLean,If,
    Then,Else,Elsif,While,For,
    Function,Return,New,In,True,
    False,Null,Identifier,INTeger,Float,
    STRing,Object,LeftBrace,RightBrace,LeftParen,
    RightParen,Comma,Dot,Assign,Equal,
    NotEqual,Not,Less,LessEqual,Plus,
    Minus,Or,And,Multiply,Power,
    Divide,Concat,Comment
}
